import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

print("Initializing Real-Data XAI GIF Studio...")

# ==========================================
# 1. KINECT V2 ANATOMY DEFINITION
# ==========================================
kinect_bones = [
    (0, 1), (1, 20), (20, 2), (2, 3),                     # Spine to Head
    (20, 4), (4, 5), (5, 6), (6, 7), (7, 21), (7, 22),    # Left Arm & Hand
    (20, 8), (8, 9), (9, 10), (10, 11), (11, 23), (11, 24), # Right Arm & Hand
    (0, 12), (12, 13), (13, 14), (14, 15),                # Left Leg
    (0, 16), (16, 17), (17, 18), (18, 19)                 # Right Leg
]

# ==========================================
# 2. DATA LOADERS
# ==========================================
def parse_single_skeleton(file_path):
    with open(file_path, 'r') as f:
        datas = f.readlines()
    if not datas: return None

    nframe = int(datas[0].strip())
    skeleton_tensor = np.zeros((nframe, 2, 25, 3), dtype=np.float32)
    
    cursor = 0
    for frame in range(nframe):
        cursor += 1
        bodycount = int(datas[cursor].strip())
        if bodycount == 0: continue
            
        for body in range(bodycount):
            cursor += 2 
            njoints_in_file = int(datas[cursor].strip())
            for joint in range(njoints_in_file):
                cursor += 1 
                if body < 2: 
                    jointinfo = datas[cursor].strip().split()
                    skeleton_tensor[frame, body, joint, :] = [float(jointinfo[0]), float(jointinfo[1]), float(jointinfo[2])]
    return skeleton_tensor

# --- AUTO-DETECTED: reads the skeleton path written by evaluate.py ---
HEATMAP_FILE  = 'extracted_xai_heatmap.npy'
SOURCE_FILE   = 'extracted_xai_source.txt'

try:
    with open(SOURCE_FILE, 'r') as f:
        SKELETON_FILE = f.read().strip()
    print(f"Using skeleton: {SKELETON_FILE}")
except FileNotFoundError:
    # Fallback: manually set the path if evaluate.py hasn't been run yet
    SKELETON_FILE = 'data/val_skeletons/S001C001P001R001A010.skeleton'
    print(f"[WARN] {SOURCE_FILE} not found — using fallback: {SKELETON_FILE}")

try:
    raw_data = parse_single_skeleton(SKELETON_FILE)
    person_sequence = raw_data[:, 0, :, :] 
    
    # Load the REAL AI Heatmap generated by evaluate.py
    xai_heatmaps = np.load(HEATMAP_FILE)
    
    # Ensure frames match
    num_frames = min(person_sequence.shape[0], xai_heatmaps.shape[0])
    print(f"Loaded and fused real data: {num_frames} frames.")
except Exception as e:
    print(f"Error loading files: {e}")
    exit()

# ==========================================
# 3. BUILD THE ANIMATION ENGINE
# ==========================================
fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(111, projection='3d')
ax.set_title("Temporal Brain XAI: Joint Attention Map", fontsize=16, fontweight='bold')
ax.set_axis_off() 

x_min, x_max = np.min(person_sequence[:, :, 0]), np.max(person_sequence[:, :, 0])
y_min, y_max = np.min(person_sequence[:, :, 1]), np.max(person_sequence[:, :, 1])
z_min, z_max = np.min(person_sequence[:, :, 2]), np.max(person_sequence[:, :, 2])

ax.set_xlim([x_min - 0.2, x_max + 0.2])
ax.set_ylim([z_min - 0.2, z_max + 0.2]) 
ax.set_zlim([y_min - 0.2, y_max + 0.2]) 
ax.view_init(elev=0, azim=-90) 

bone_lines = [ax.plot([], [], [], color='black', linewidth=3, zorder=1)[0] for _ in kinect_bones]
joint_scatter = ax.scatter([], [], [], s=120, zorder=2, edgecolors='white', linewidth=1.5)

# Fixed the deprecation warning from your notebook
cmap = plt.colormaps['coolwarm']

def update(frame_idx):
    current_skeleton = person_sequence[frame_idx]
    current_heat = xai_heatmaps[frame_idx]
    
    for i, (j1, j2) in enumerate(kinect_bones):
        x_vals = [current_skeleton[j1, 0], current_skeleton[j2, 0]]
        y_vals = [current_skeleton[j1, 2], current_skeleton[j2, 2]] 
        z_vals = [current_skeleton[j1, 1], current_skeleton[j2, 1]] 
        bone_lines[i].set_data(x_vals, y_vals)
        bone_lines[i].set_3d_properties(z_vals)
        
    joint_scatter._offsets3d = (current_skeleton[:, 0], current_skeleton[:, 2], current_skeleton[:, 1])
    
    colors = cmap(current_heat)
    joint_scatter.set_color(colors)
    joint_scatter.set_edgecolor('black') 
    
    return bone_lines + [joint_scatter]

print("Rendering GIF with real XAI data... (This may take 30-60 seconds)")
ani = FuncAnimation(fig, update, frames=num_frames, interval=33, blit=False)

gif_filename = 'real_xai_output.gif'
ani.save(gif_filename, writer='pillow', fps=30)
plt.close()

print(f"Success! Animation saved locally as: {gif_filename}")